In [1]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn

In [2]:
pwd

'C:\\Users\\Erik\\Documents\\Projects\\Tutorials\\repos\\machine_learning\\Ch01_Intro'

In [13]:
# Load data
oecd_bli = pd.read_csv(r"./data/2017_OECD_better_life_index.csv", usecols=['Country', 'Value'])

In [14]:
oecd_bli.head()

          Country  Value
0       Australia    4.3
1         Austria    2.7
2         Belgium    4.8
3          Canada    3.9
4  Czech Republic    1.8

In [15]:
gdp_per_capita = pd.read_csv(r"./data/AllYears_imf_gdp_per_capita.csv", usecols=['GDP per capita, current prices (U.S. dollars per capita)', '2017'])

In [16]:
pd.merge(left=gdp_per_capita, right=oecd_bli, left_on='GDP per capita, current prices (U.S. dollars per capita)', right_on='Country')

,"GDP per capita, current prices (U.S. dollars per capita)",2017,Country,Value
0,Australia,56135.416,Australia,4.30
1,Australia,56135.416,Australia,2.70
2,Australia,56135.416,Australia,2.70
3,Australia,56135.416,Australia,2.70
4,Australia,56135.416,Australia,63.60
5,Australia,56135.416,Australia,79.20
6,Australia,56135.416,Australia,49.90
7,Australia,56135.416,Australia,1.10
8,Australia,56135.416,Australia,1.10
9,Australia,56135.416,Australia,1.10
10,Australia,56135.416,Australia,20.00
11,Australia,56135.416,Australia,20.00
12,Australia,56135.416,Australia,20.00
13,Australia,56135.416,Australia,2.30
14,Australia,56135.416,Australia,2.30
15,Australia,56135.416,Australia,2.30
16,Australia,56135.416,Australia,33417.00
17,Australia,56135.416,Australia,33417.00
18,Australia,56135.416,Australia,33417.00
19,Australia,56135.416,Australia,68338.00
20,Australia,56135.416,Australia,12068.00
21,Australia,56135.416,Australia,57462.00
22,Australia,56135.416,Australia,57462.00
23,Australia,56135.416,Australia,57462.00
24,Australia,56135.416,Australia,72.00
25,Australia,56135.416,Australia,78.00
26,Australia,56135.416,Australia,67.00
27,Australia,56135.416,Australia,84.00
28,Australia,56135.416,Australia,58.00
29,Australia,56135.416,Australia,1.36
...,...,...,...,...
3118,United States,59495.336,United States,10.00
3119,United States,59495.336,United States,84.00
3120,United States,59495.336,United States,86.00
3121,United States,59495.336,United States,83.00
3122,United States,59495.336,United States,68.00
3123,United States,59495.336,United States,67.00
3124,United States,59495.336,United States,69.00
3125,United States,59495.336,United States,76.00
3126,United States,59495.336,United States,54.00
3127,United States,59495.336,United States,78.80
3128,United States,59495.336,United States,76.30
3129,United States,59495.336,United States,81.20
3130,United States,59495.336,United States,88.00
3131,United States,59495.336,United States,89.00
3132,United States,59495.336,United States,88.00
3133,United States,59495.336,United States,96.00
3134,United States,59495.336,United States,74.00
3135,United States,59495.336,United States,6.90
3136,United States,59495.336,United States,6.90
3137,United States,59495.336,United States,7.00
3138,United States,59495.336,United States,7.40
3139,United States,59495.336,United States,4.90
3140,United States,59495.336,United States,7.70
3141,United States,59495.336,United States,2.10
3142,United States,59495.336,United States,11.45
3143,United States,59495.336,United States,15.70
3144,United States,59495.336,United States,6.86
3145,United States,59495.336,United States,14.44
3146,United States,59495.336,United States,14.48
3147,United States,59495.336,United States,14.39

In [7]:
def prepare_country_stats(oecd_bli, gdp_per_capita):
    oecd_bli = oecd_bli[oecd_bli["INEQUALITY"]=="TOT"]
    oecd_bli = oecd_bli.pivot(index="Country", columns="Indicator", values="Value")
    gdp_per_capita.rename(columns={"2017": "GDP per capita"}, inplace=True)
    gdp_per_capita.set_index("Country", inplace=True)
    full_country_stats = pd.merge(left=oecd_bli, right=gdp_per_capita,
                                  left_index=True, right_index=True)
    full_country_stats.sort_values(by="GDP per capita", inplace=True)
    remove_indices = [0, 1, 6, 8, 33, 34, 35]
    keep_indices = list(set(range(36)) - set(remove_indices))
    return full_country_stats[["GDP per capita", 'Life satisfaction']].iloc[keep_indices]